# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa4ab31f82876611e23c36a580f725f8a40826b471555ad0796fee3c98f0bbf5d968a269a4623f754bceacde79c37de96d558a4dc8f8b1cb9ac896d0bb982db5

test:
  secret_key_base: ca794a703d206f88aae7fa1ad2fa15aad162028f8e4c5caee1b187111949ed1800f46893e5fb669d0b204b5d92df416177ffa69b702d5c733a497c180bc2327f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
